title: "Weather Report"
author: "Vittal Siddaiah"
description: "Impossible is Nothing, We are only Limited by our Imagination..."
more: "read more »"
url: "https://github.com/vittalsiddaiah"
baseurl: "/WeatherReport.github.io"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
#  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  #- twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/vittalsiddaiah/WeatherReport.github.io"
  - envelope: "mailto:vittal.siddaiah@gmail.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: 
  - jekyll-feed
  - jekyll-paginate
